
import pandas as pd
import matplotlib.pyplot as plt
import os

# --- Setup: Generate Dummy Data ---
print("Setting up dummy data...")

# 1. data.xlsx
df_data = pd.DataFrame({
    'category': ['A', 'B', 'C', 'A', 'B'],
    'value': [10, 20, 15, 12, 18]
})
df_data.to_excel("data.xlsx", sheet_name="Sheet1", index=False)

# 2. workbook.xlsx (multiple sheets)
with pd.ExcelWriter("workbook.xlsx") as writer:
    df_data.to_excel(writer, sheet_name="Sheet1", index=False)
    df_data.to_excel(writer, sheet_name="Sheet2", index=False)

# 3. sales.xlsx
df_sales = pd.DataFrame({
    'region': ['North', 'South', 'East', 'West', 'North'],
    'sales': [12000, 8000, 15000, 5000, 11000],
    'revenue': [15000, 10000, 18000, 6000, 14000],
    'cost': [10000, 7000, 12000, 4000, 9000],
    'customer_id': [1, 2, 3, 4, 1]
})
df_sales.to_excel("sales.xlsx", index=False)

# 4. output.xlsx generated by script, skipping setup

# 5. sales_data.xlsx (for pivot)
df_pivot = pd.DataFrame({
    'region': ['North', 'North', 'South', 'South'],
    'product': ['A', 'B', 'A', 'B'],
    'sales': [100, 200, 150, 250]
})
df_pivot.to_excel("sales_data.xlsx", index=False)

# 6. messy_data.xlsx
df_messy = pd.DataFrame({
    'name': [' Alice ', 'Bob', 'Alice', None],
    'amount': [100, '200', 100, 50],
    'date': ['2023-01-01', '2023-01-02', '2023-01-01', 'invalid']
})
df_messy.to_excel("messy_data.xlsx", index=False)

# 7. sales_q1.xlsx, sales_q2.xlsx
df_q1 = pd.DataFrame({'sales': [100, 200]})
df_q2 = pd.DataFrame({'sales': [300, 400]})
df_q1.to_excel("sales_q1.xlsx", index=False)
df_q2.to_excel("sales_q2.xlsx", index=False)

# 8. customers.xlsx
df_customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Customer A', 'Customer B', 'Customer C', 'Customer D']
})
df_customers.to_excel("customers.xlsx", index=False)

print("Data setup complete.\n")

# --- Execute SKILL.md Examples ---

print("--- 1. Reading Excel files ---")
# Read Excel file
df = pd.read_excel("data.xlsx", sheet_name="Sheet1")
# Display first few rows
print(df.head())
# Basic statistics
print(df.describe())
print("\n")


print("--- 2. Reading multiple sheets ---")
# Read all sheets
excel_file = pd.ExcelFile("workbook.xlsx")
for sheet_name in excel_file.sheet_names:
    df = pd.read_excel(excel_file, sheet_name=sheet_name)
    print(f"\n{sheet_name}:")
    print(df.head())
print("\n")


print("--- 3. Data analysis ---")
df = pd.read_excel("sales.xlsx")
# Group by and aggregate
sales_by_region = df.groupby("region")["sales"].sum()
print("Sales by region:")
print(sales_by_region)
# Filter data
high_sales = df[df["sales"] > 10000]
print("High sales:")
print(high_sales)
# Calculate metrics
df["profit_margin"] = (df["revenue"] - df["cost"]) / df["revenue"]
# Sort by column
df_sorted = df.sort_values("sales", ascending=False)
print("Sorted with metrics:")
print(df_sorted.head())
print("\n")


print("--- 4. Creating Excel files ---")
df_new = pd.DataFrame({
    "Product": ["A", "B", "C"],
    "Sales": [100, 200, 150],
    "Profit": [20, 40, 30]
})
# Write to Excel
writer = pd.ExcelWriter("output.xlsx", engine="openpyxl")
df_new.to_excel(writer, sheet_name="Sales", index=False)
# Get worksheet for formatting
worksheet = writer.sheets["Sales"]
# Auto-adjust column widths
for column in worksheet.columns:
    max_length = 0
    column_letter = column[0].column_letter
    for cell in column:
        try:
            if len(str(cell.value)) > max_length:
                max_length = len(str(cell.value))
        except:
            pass
    worksheet.column_dimensions[column_letter].width = max_length + 2
writer.close()
print("Created output.xlsx\n")


print("--- 5. Pivot tables ---")
df = pd.read_excel("sales_data.xlsx")
# Create pivot table
pivot = pd.pivot_table(
    df,
    values="sales",
    index="region",
    columns="product",
    aggfunc="sum",
    fill_value=0
)
print("Pivot table:")
print(pivot)
# Save pivot table
pivot.to_excel("pivot_report.xlsx")
print("Saved pivot_report.xlsx\n")


print("--- 6. Charts and visualization ---")
df = pd.read_excel("data.xlsx") # Reusing data.xlsx which has category/value
# Create bar chart
plt.figure() # New figure
df.plot(x="category", y="value", kind="bar")
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("chart.png")
print("Saved chart.png")

# Create pie chart
plt.figure() # New figure
df.set_index("category")["value"].plot(kind="pie", autopct="%1.1f%%")
plt.title("Market Share")
plt.ylabel("")
plt.savefig("pie_chart.png")
print("Saved pie_chart.png\n")


print("--- 7. Data cleaning ---")
df = pd.read_excel("messy_data.xlsx")
# Remove duplicates
df = df.drop_duplicates()
# Handle missing values
df = df.fillna(0)  # or df.dropna()
# Remove whitespace
df["name"] = df["name"].str.strip()
# Convert data types
df["date"] = pd.to_datetime(df["date"], errors='coerce') # Added errors='coerce' to match skill logic for amount but applied to date which had 'invalid'
df["amount"] = pd.to_numeric(df["amount"], errors="coerce")
# Save cleaned data
df.to_excel("cleaned_data.xlsx", index=False)
print("Saved cleaned_data.xlsx\n")


print("--- 8. Merging and joining ---")
# Read multiple files
df1 = pd.read_excel("sales_q1.xlsx")
df2 = pd.read_excel("sales_q2.xlsx")
# Concatenate vertically
combined = pd.concat([df1, df2], ignore_index=True)
print("Combined data:")
print(combined)

# Merge on common column
customers = pd.read_excel("customers.xlsx")
sales = pd.read_excel("sales.xlsx")
merged = pd.merge(sales, customers, on="customer_id", how="left")
merged.to_excel("merged_data.xlsx", index=False)
print("Saved merged_data.xlsx\n")


print("--- 9. Advanced formatting ---")
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font

# Create Excel file
df = pd.DataFrame({
    "Product": ["A", "B", "C"],
    "Sales": [100, 200, 150]
})
df.to_excel("formatted.xlsx", index=False)

# Load workbook for formatting
wb = load_workbook("formatted.xlsx")
ws = wb.active

# Apply conditional formatting
red_fill = PatternFill(start_color="FF0000", end_color="FF0000", fill_type="solid")
green_fill = PatternFill(start_color="00FF00", end_color="00FF00", fill_type="solid")

for row in range(2, len(df) + 2):
    cell = ws[f"B{row}"]
    # Check if value is numeric before comparing
    if isinstance(cell.value, (int, float)) and cell.value < 150:
         cell.fill = red_fill
    else:
         cell.fill = green_fill

# Bold headers
for cell in ws[1]:
    cell.font = Font(bold=True)

wb.save("formatted.xlsx")
print("Saved formatted.xlsx\n")

print("All skill demonstrations completed successfully.")
