name: Portfolio Monitor

on:
  schedule:
    - cron: '0 * * * *'  # 每小時自動執行一次
  workflow_dispatch:      # 也可以手動在網頁點擊執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas fubon-neo

      - name: Run Script
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
          GAS_URL: ${{ secrets.GAS_URL }}
        run: python portfolio-tracker/gas3.py
